twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : cmd_vel
        timeout : 0.5
        priority: 100
      joystick:
        topic   : joy_vel
        timeout : 0.5
        priority: 99
      keyboard: 
        topic   : key_vel
        timeout : 0.5
        priority: 90